exports.AMQPLibUtil = require './AMQPLibUtil'
exports.Channel = require './Channel'
exports.ConfirmChannel = require './ConfirmChannel'
exports.Connection = require './Connection'
exports.Consume = require './Consume'
exports.Consumer = require './Consumer'
exports.Exchange = require './Exchange'
exports.Message = require './Message'
exports.Service = require './Service'
exports.Publish = require './Publish'
exports.Queue = require './Queue'
exports.QueueBinding = require './QueueBinding'
exports.Schema = require './Schema'
exports.Service = require './Service'

exports.createService = (properties) -> new exports.Service properties
