// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty;

  module.exports = {
    getOptionsForPublish: function(params) {
      var key, options, val, _ref;
      options = {};
      _ref = params.message.properties;
      for (key in _ref) {
        if (!__hasProp.call(_ref, key)) continue;
        val = _ref[key];
        if (val != null) {
          options[key] = val;
        }
      }
      if (params.mandatory != null) {
        options.mandatory = params.mandatory;
      }
      return options;
    },
    createLibMessage: function(message) {
      return {
        fields: message.delivery,
        properties: message.properties,
        content: message.payload
      };
    }
  };

}).call(this);

/*
//@ sourceMappingURL=AMQPLibUtil.map
*/
