// Generated by CoffeeScript 1.6.3
(function() {
  var AMQPLibUtil, Channel, ConfirmChannel, Publish, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Channel = require('./Channel');

  AMQPLibUtil = require('./AMQPLibUtil');

  Publish = require('./Publish');

  ConfirmChannel = (function(_super) {
    __extends(ConfirmChannel, _super);

    function ConfirmChannel() {
      _ref = ConfirmChannel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ConfirmChannel.prototype.publish = function(params, callback) {
      var options;
      params = new Publish(params);
      options = AMQPLibUtil.getOptionsForPublish(params);
      return this.wrapped.publish(params.exchangeName, params.routingKey, params.message.payload, options, callback);
    };

    return ConfirmChannel;

  })(Channel);

  module.exports = ConfirmChannel;

}).call(this);

/*
//@ sourceMappingURL=ConfirmChannel.map
*/
