// Generated by CoffeeScript 1.6.3
(function() {
  var Channel, Connection, When;

  When = require('when');

  Channel = require('./Channel');

  Connection = (function() {
    function Connection(properties) {
      if (properties == null) {
        properties = {};
      }
      this.uri = properties.uri;
      this.promiseForConnection = properties.promiseForConnection;
    }

    Connection.prototype.createChannel = function() {
      var getPromiseForChannel, promiseForChannel;
      getPromiseForChannel = function(connection) {
        var deferred;
        deferred = When.defer();
        connection.createChannel(function(error, channel) {
          if (error != null) {
            return deferred.reject(error);
          }
          return deferred.resolve(channel);
        });
        return deferred.promise;
      };
      promiseForChannel = When(this.promiseForConnection).then(getPromiseForChannel);
      return new Channel({
        promiseForChannel: promiseForChannel
      });
    };

    Connection.prototype.close = function(callback) {
      var closeConnection;
      closeConnection = function(connection) {
        return connection.close(callback);
      };
      return this.promiseForConnection.then(closeConnection)["catch"](callback);
    };

    return Connection;

  })();

  module.exports = Connection;

}).call(this);

/*
//@ sourceMappingURL=Connection.map
*/
