// Generated by CoffeeScript 1.6.3
(function() {
  var Channel, Connection, Publisher;

  Channel = require('./Channel');

  Publisher = require('./Publisher');

  Connection = (function() {
    function Connection(properties) {
      if (properties == null) {
        properties = {};
      }
      this.uri = properties.uri;
      this.wrapped = properties.wrapped;
    }

    Connection.prototype.createChannel = function(callback) {
      return this.wrapped.createChannel(function(error, wrapped) {
        var channel;
        if (error != null) {
          return callback(error);
        }
        channel = new Channel({
          wrapped: wrapped
        });
        return callback(null, channel);
      });
    };

    Connection.prototype.createPublisher = function(callback) {
      return this.wrapped.createConfirmChannel(function(error, wrapped) {
        var publisher;
        if (error != null) {
          return callback(error);
        }
        publisher = new Publisher({
          wrapped: wrapped
        });
        return callback(null, publisher);
      });
    };

    Connection.prototype.close = function(callback) {
      return this.wrapped.close(function(error) {
        return callback(error);
      });
    };

    return Connection;

  })();

  module.exports = Connection;

}).call(this);

/*
//@ sourceMappingURL=Connection.map
*/
