// Generated by CoffeeScript 1.6.3
(function() {
  var Consume;

  Consume = (function() {
    function Consume(properties) {
      if (properties == null) {
        properties = {};
      }
      this.noAck = properties.noAck;
      this.exclusive = properties.exclusive;
      this.priority = properties.priority;
      this["arguments"] = properties["arguments"];
      this.prefetch = properties.prefetch;
      this.queueName = properties.queueName;
      this.consumerTag = properties.consumerTag;
      this.handleMessage = properties.handleMessage;
      this.setDefaults();
    }

    Consume.prototype.setDefaults = function() {
      if (this.prefetch == null) {
        this.prefetch = 1;
      }
      if (this.exclusive == null) {
        this.exclusive = false;
      }
      return this.noAck != null ? this.noAck : this.noAck = false;
    };

    return Consume;

  })();

  module.exports = Consume;

}).call(this);

/*
//@ sourceMappingURL=Consume.map
*/
