// Generated by CoffeeScript 1.6.3
(function() {
  var Consumer;

  Consumer = (function() {
    function Consumer(properties) {
      if (properties == null) {
        properties = {};
      }
      this.prefetch = properties.prefetch;
      this.queueName = properties.queueName;
      this.handleMessage = properties.handleMessage;
      this.channel = properties.channel;
      this.consumerTag = properties.consumerTag;
      this.setDefaults();
    }

    Consumer.prototype.setDefaults = function() {
      return this.prefetch != null ? this.prefetch : this.prefetch = 1;
    };

    Consumer.prototype.handleMessage = function(message) {
      throw Error("Not Implemented");
    };

    Consumer.prototype.cancel = function(callback) {
      return this.channel.cancel(this.consumerTag, callback);
    };

    return Consumer;

  })();

  module.exports = Consumer;

}).call(this);

/*
//@ sourceMappingURL=Consumer.map
*/
