// Generated by CoffeeScript 1.6.3
(function() {
  var Exchange, ExchangeOptions;

  Exchange = (function() {
    function Exchange(properties) {
      if (properties == null) {
        properties = {};
      }
      this.name = properties.name;
      this.type = properties.type;
      this.setOptions(properties.options);
    }

    Exchange.prototype.setOptions = function(options) {
      return this.options = new ExchangeOptions(options);
    };

    return Exchange;

  })();

  ExchangeOptions = (function() {
    function ExchangeOptions(properties) {
      if (properties == null) {
        properties = {};
      }
      this.durable = properties.durable;
      this.internal = properties.internal;
      this.autoDelete = properties.autoDelete;
      this.alternateExchange = properties.alternateExchange;
      this.setDefaults();
    }

    ExchangeOptions.prototype.setDefaults = function() {
      if (this.durable == null) {
        this.durable = false;
      }
      if (this.internal == null) {
        this.internal = false;
      }
      if (this.autoDelete == null) {
        return this.autoDelete = false;
      }
    };

    return ExchangeOptions;

  })();

  Exchange.Options = ExchangeOptions;

  module.exports = Exchange;

}).call(this);

/*
//@ sourceMappingURL=Exchange.map
*/
