// Generated by CoffeeScript 1.6.3
(function() {
  var AMQPLib, Connection, When;

  When = require('when');

  AMQPLib = require('amqplib/callback_api');

  Connection = require('./Connection');

  exports.Queue = require('./Queue');

  exports.Exchange = require('./Exchange');

  exports.Schema = require('./Schema');

  exports.Channel = require('./Channel');

  exports.Connection = require('./Connection');

  exports.connect = function(uri) {
    var deferred;
    deferred = When.defer();
    AMQPLib.connect(uri, function(error, connection) {
      if (error != null) {
        return deferred.reject(error);
      }
      return deferred.resolve(connection);
    });
    return new Connection({
      uri: uri,
      promiseForConnection: deferred.promise
    });
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
