// Generated by CoffeeScript 1.6.3
(function() {
  exports.Service = require('./Service');

  exports.Queue = require('./Queue');

  exports.Exchange = require('./Exchange');

  exports.Schema = require('./Schema');

  exports.Channel = require('./Channel');

  exports.Connection = require('./Connection');

  exports.Service = require('./Service');

  exports.Message = require('./Message');

  exports.createService = function(properties) {
    return new exports.Service(properties);
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
