// Generated by CoffeeScript 1.6.3
(function() {
  var Message,
    __slice = [].slice;

  Message = (function() {
    function Message(properties) {
      if (properties == null) {
        properties = {};
      }
      this.messageId = properties.messageId;
      this.routingKey = properties.routingKey;
      this.expiration = properties.expiration;
      this.userId = properties.userId;
      this.mandatory = properties.mandatory;
      this.persistent = properties.persistent;
      this.immediate = properties.immediate;
      this.contentType = properties.contentType;
      this.contentEncoding = properties.contentEncoding;
      this.priority = properties.priority;
      this.correlationId = properties.correlationId;
      this.replyTo = properties.replyTo;
      this.timestamp = properties.timestamp;
      this.type = properties.type;
      this.appId = properties.appId;
      this.payload = properties.payload;
      this.setHeaders(properties.headers);
      this.setDefaults();
    }

    Message.prototype.setDefaults = function() {
      if (this.mandatory == null) {
        this.mandatory = false;
      }
      if (this.persistent == null) {
        this.persistent = false;
      }
      return this.immediate != null ? this.immediate : this.immediate = false;
    };

    Message.prototype.setHeaders = function(headers) {
      if (headers == null) {
        headers = {};
      }
      return this.headers = headers;
    };

    Message.prototype.carbonCopy = function() {
      var current, routingKeys;
      routingKeys = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      current = this.headers.CC != null ? this.headers.CC : [];
      return this.headers.CC = current.concat(routingKeys);
    };

    Message.prototype.blindCarbonCopy = function() {
      var current, routingKeys;
      routingKeys = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      current = this.headers.BCC != null ? this.headers.BCC : [];
      return this.headers.BCC = current.concat(routingKeys);
    };

    return Message;

  })();

  module.exports = Message;

}).call(this);

/*
//@ sourceMappingURL=Message.map
*/
