// Generated by CoffeeScript 1.6.3
(function() {
  var BasicDeliver, BasicProperties, Message;

  BasicProperties = (function() {
    function BasicProperties(properties) {
      if (properties == null) {
        properties = {};
      }
      this.appId = properties.appId;
      this.contentEncoding = properties.contentEncoding;
      this.contentType = properties.contentType;
      this.correlationId = properties.correlationId;
      this.deliveryMode = properties.deliveryMode;
      this.expiration = properties.expiration;
      this.messageId = properties.messageId;
      this.priority = properties.priority;
      this.replyTo = properties.replyTo;
      this.timestamp = properties.timestamp;
      this.type = properties.type;
      this.userId = properties.userId;
      this.setHeaders(properties.headers);
    }

    BasicProperties.prototype.setHeaders = function(headers) {
      if (headers == null) {
        headers = {};
      }
      return this.headers = headers;
    };

    return BasicProperties;

  })();

  BasicDeliver = (function() {
    function BasicDeliver(properties) {
      if (properties == null) {
        properties = {};
      }
      this.deliveryTag = properties.deliveryTag;
      this.consumerTag = properties.consumerTag;
      this.exchange = properties.exchange;
      this.routingKey = properties.routingKey;
      this.redelivered = properties.redelivered;
    }

    return BasicDeliver;

  })();

  Message = (function() {
    function Message(properties) {
      if (properties == null) {
        properties = {};
      }
      this.setProperties(properties.properties);
      this.setDelivery(properties.delivery);
      this.setPayload(properties.payload);
    }

    Message.prototype.setDelivery = function(properties) {
      return this.delivery = new BasicDeliver(properties);
    };

    Message.prototype.setProperties = function(properties) {
      return this.properties = new BasicProperties(properties);
    };

    Message.prototype.setPayload = function(buffer) {
      return this.payload = buffer;
    };

    return Message;

  })();

  module.exports = Message;

}).call(this);

/*
//@ sourceMappingURL=Message.map
*/
