// Generated by CoffeeScript 1.6.3
(function() {
  var Publisher, getOptionsForPublish,
    __hasProp = {}.hasOwnProperty;

  getOptionsForPublish = function(message) {
    var key, options, value;
    options = {
      messageId: message.messageId,
      expiration: message.expiration,
      userId: message.userId,
      mandatory: message.mandatory,
      persistent: message.persistent,
      immediate: message.immediate,
      contentType: message.contentType,
      contentEncoding: message.contentEncoding,
      priority: message.priority,
      correlationId: message.correlationId,
      replyTo: message.replyTo,
      timestamp: message.timestamp,
      type: message.type,
      headers: message.headers
    };
    for (key in options) {
      if (!__hasProp.call(options, key)) continue;
      value = options[key];
      if (value === void 0) {
        delete options[key];
      }
    }
    return options;
  };

  Publisher = (function() {
    function Publisher(properties) {
      if (properties == null) {
        properties = {};
      }
      this.wrapped = properties.wrapped;
    }

    Publisher.prototype.publish = function(exchangeName, message, callback) {
      var content, done, key, options;
      key = message.routingKey;
      content = message.payload;
      options = getOptionsForPublish(message);
      done = function(error) {
        return callback(error, message);
      };
      return this.wrapped.publish(exchangeName, key, content, options, done);
    };

    return Publisher;

  })();

  module.exports = Publisher;

}).call(this);

/*
//@ sourceMappingURL=Publisher.map
*/
