// Generated by CoffeeScript 1.6.3
(function() {
  var Message, Publish;

  Message = require('./Message');

  Publish = (function() {
    function Publish(properties) {
      if (properties == null) {
        properties = {};
      }
      this.exchangeName = properties.exchangeName;
      this.routingKey = properties.routingKey;
      this.mandatory = properties.mandatory;
      this.setMessage(properties.message);
      this.setDefaults();
    }

    Publish.prototype.setMessage = function(message) {
      if (message instanceof Message) {
        return this.message = message;
      }
      return this.message = new Message(message);
    };

    Publish.prototype.setDefaults = function() {
      return this.mandatory != null ? this.mandatory : this.mandatory = false;
    };

    return Publish;

  })();

  module.exports = Publish;

}).call(this);

/*
//@ sourceMappingURL=Publish.map
*/
