// Generated by CoffeeScript 1.6.3
(function() {
  var QueueBinding;

  QueueBinding = (function() {
    function QueueBinding(properties) {
      if (properties == null) {
        properties = {};
      }
      this.queueName = properties.queueName;
      this.exchangeName = properties.exchangeName;
      this.pattern = properties.pattern;
      this["arguments"] = properties["arguments"];
    }

    return QueueBinding;

  })();

  module.exports = QueueBinding;

}).call(this);

/*
//@ sourceMappingURL=QueueBinding.map
*/
