// Generated by CoffeeScript 1.6.3
(function() {
  var Exchange, Queue, Schema;

  Queue = require('./Queue');

  Exchange = require('./Exchange');

  Schema = (function() {
    function Schema(properties) {
      if (properties == null) {
        properties = {};
      }
      this.exchanges = properties.exchanges;
      this.queues = properties.queues;
      this.setDefaults();
    }

    Schema.prototype.setDefaults = function() {
      if (this.exchanges == null) {
        this.exchanges = [];
      }
      if (this.queues == null) {
        return this.queues = [];
      }
    };

    Schema.prototype.defineExchange = function(name, type, options) {
      var exchange;
      exchange = new Exchange({
        name: name,
        type: type,
        options: options
      });
      this.exchanges.push(exchange);
      return exchange;
    };

    Schema.prototype.defineQueue = function(name, options) {
      var queue;
      queue = new Queue({
        name: name,
        options: options
      });
      this.queues.push(queue);
      return queue;
    };

    return Schema;

  })();

  module.exports = Schema;

}).call(this);

/*
//@ sourceMappingURL=Schema.map
*/
