// Generated by CoffeeScript 1.6.3
(function() {
  var AMQPLib, AMQPService, Connection, When;

  When = require('when');

  AMQPLib = require('amqplib/callback_api');

  Connection = require('./Connection');

  AMQPService = (function() {
    function AMQPService() {}

    AMQPService.prototype.connect = function(uri) {
      var deferred;
      deferred = When.defer();
      AMQPLib.connect(uri, function(error, connection) {
        if (error != null) {
          return deferred.reject(error);
        }
        return deferred.resolve(connection);
      });
      return new Connection({
        uri: uri,
        promiseForConnection: deferred.promise
      });
    };

    return AMQPService;

  })();

  module.exports = AMQPService;

}).call(this);

/*
//@ sourceMappingURL=Service.map
*/
